# Site settings
title: Isaac Kuek
email: kuek.isaac@gmail.com
description: "Isaac Kuek, an undergraduate in the Informatics HCI program at UW, Seattle. Experimenting and learning UX applications in websites, mobile apps and other emerging technologies."
baseurl: ""
url: "http://isaack.me"
username: isaackuek

# Build settings
markdown: kramdown
permalink: pretty

gems: [jekyll-assets, sass, bourbon, neat]

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images  